# Generated by Django 4.2.11 on 2024-04-27 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='degree',
            fields=[
                ('degree_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='discipline',
            fields=[
                ('discipline_id', models.AutoField(primary_key=True, serialize=False)),
                ('discipline_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employee_qualification',
            fields=[
                ('employee_qualification_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_makrs', models.IntegerField()),
                ('marks_obtained', models.IntegerField()),
                ('passing_year', models.IntegerField()),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.degree')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.discipline')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
        ),
    ]
