# Generated by Django 4.2.11 on 2024-04-27 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_degree_discipline_employee_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='relation',
            fields=[
                ('relation_id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_family_members',
            fields=[
                ('emp_fam_mem_id', models.AutoField(primary_key=True, serialize=False)),
                ('fam_mem_name_name', models.CharField(max_length=100)),
                ('fam_mem_dob', models.DateField()),
                ('fam_mem_gender', models.CharField(max_length=30)),
                ('fam_mem_cnic', models.IntegerField()),
                ('fam_mem_living_status', models.CharField(max_length=6)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.relation')),
            ],
        ),
    ]
