# Generated by Django 4.2.11 on 2024-07-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0007_class_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_system',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(upload_to='profile_picture/')),
            ],
        ),
    ]
